import { View, Text } from '@react-pdf/renderer';
import { pdfStyles } from '../styles/pdfStyles';

interface PdfFooterProps {
  pageNumber: number;
  totalPages: number;
}

export function PdfFooter({ pageNumber, totalPages }: PdfFooterProps) {
  return (
    <View style={pdfStyles.footer}>
      {/* Left: Company Info */}
      <View>
        <Text style={{ fontSize: 8, color: '#666666' }}>
          Bisedge South Africa (Pty) Ltd | +27 11 123 4567 | quotes@bisedge.co.za
        </Text>
      </View>

      {/* Right: Page Number */}
      <View>
        <Text style={{ fontSize: 8, color: '#666666' }}>
          Page {pageNumber} of {totalPages}
        </Text>
      </View>
    </View>
  );
}

export function PdfFooterSimple() {
  return (
    <View style={pdfStyles.footer}>
      <View style={{ width: '100%', alignItems: 'center' }}>
        <Text style={{ fontSize: 8, color: '#999999' }}>
          Generated by Bisedge Quotation System | This is a system-generated document
        </Text>
      </View>
    </View>
  );
}
