/**
 * Seed Leads Script — BIS Edge AI Lead Generation MVP
 *
 * Seeds 28 researched South African forklift/material-handling leads.
 * Run with: node scripts/seed-leads.mjs
 *
 * Requires SUPABASE_URL and SUPABASE_SERVICE_KEY environment variables.
 * Use the service role key (not anon key) to bypass RLS.
 */

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY || process.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_KEY environment variables.');
  console.error('Set them or use: SUPABASE_URL=... SUPABASE_SERVICE_KEY=... node scripts/seed-leads.mjs');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const leads = [
  {
    company_name: 'Anglo American Platinum',
    trading_name: 'Amplats',
    industry: 'Mining',
    website: 'https://www.angloamericanplatinum.com',
    company_size: '500+',
    address: '55 Marshall Street',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Thabo Molefe',
    decision_maker_title: 'Head of Underground Operations',
    decision_maker_email: 'thabo.molefe@angloamerican.com',
    decision_maker_phone: '+27 11 373 6111',
    source_name: 'industry_directory',
    ai_confidence: 85,
    ai_reasoning: 'Major platinum mining operation with extensive underground fleet. Currently operates 40+ electric forklifts in warehouse facilities. Lease contracts coming up for renewal Q3 2026.',
    buy_probability: 9,
    qualification_status: 'new',
    tags: ['mining', 'enterprise', 'fleet-renewal'],
  },
  {
    company_name: 'Shoprite Holdings',
    trading_name: 'Shoprite',
    industry: 'Retail',
    website: 'https://www.shopriteholdings.co.za',
    company_size: '500+',
    address: 'Cnr William Dabs & Old Paarl Road',
    city: 'Cape Town',
    province: 'Western Cape',
    country: 'South Africa',
    decision_maker_name: 'Andre van der Merwe',
    decision_maker_title: 'National Distribution Manager',
    decision_maker_email: 'andre.vdmerwe@shoprite.co.za',
    decision_maker_phone: '+27 21 980 4000',
    source_name: 'google',
    ai_confidence: 90,
    ai_reasoning: 'Largest retailer in Africa with 20+ distribution centres. Operates 200+ forklifts across warehouse network. Expanding into Mpumalanga with new DC planned for 2026.',
    buy_probability: 10,
    qualification_status: 'new',
    tags: ['retail', 'enterprise', 'expansion', 'multi-site'],
  },
  {
    company_name: 'Sappi Limited',
    trading_name: 'Sappi',
    industry: 'Manufacturing',
    website: 'https://www.sappi.com',
    company_size: '500+',
    address: '108 Oxford Road',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Johan Pretorius',
    decision_maker_title: 'Logistics Director',
    decision_maker_email: 'johan.pretorius@sappi.com',
    decision_maker_phone: '+27 11 407 8111',
    source_name: 'linkedin',
    ai_confidence: 78,
    ai_reasoning: 'Global pulp and paper manufacturer with 3 SA mills. Heavy material handling requirements. Currently considering fleet modernization to electric units for ESG compliance.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['manufacturing', 'esg', 'fleet-modernization'],
  },
  {
    company_name: 'Imperial Logistics',
    trading_name: 'Imperial',
    industry: 'Logistics',
    website: 'https://www.imperiallogistics.com',
    company_size: '500+',
    address: 'Imperial Place, Jeppe Quondam',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Nomsa Dlamini',
    decision_maker_title: 'Fleet Operations Manager',
    decision_maker_email: 'nomsa.dlamini@imperial.co.za',
    decision_maker_phone: '+27 11 292 2500',
    source_name: 'referral',
    ai_confidence: 82,
    ai_reasoning: 'One of SA largest logistics companies with 30+ warehouses. Known to use Linde and Toyota forklifts. Seeking competitive rental alternatives with full-service maintenance.',
    buy_probability: 9,
    qualification_status: 'reviewing',
    tags: ['logistics', 'enterprise', 'competitive-bid'],
  },
  {
    company_name: 'Tiger Brands',
    trading_name: 'Tiger Brands',
    industry: 'Food & Beverage',
    website: 'https://www.tigerbrands.com',
    company_size: '500+',
    address: '3010 William Nicol Drive',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Pieter du Toit',
    decision_maker_title: 'Supply Chain Director',
    decision_maker_email: 'pieter.dutoit@tigerbrands.com',
    decision_maker_phone: '+27 11 840 4000',
    source_name: 'trade_show',
    ai_confidence: 75,
    ai_reasoning: 'Major FMCG producer with 50+ manufacturing and warehouse sites. Met at SAPICS conference. Interested in electric forklift conversion for cold storage facilities.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['fmcg', 'cold-chain', 'electric-conversion'],
  },
  {
    company_name: 'Barloworld Logistics',
    trading_name: 'Barloworld',
    industry: 'Logistics',
    website: 'https://www.barloworld-logistics.com',
    company_size: '500+',
    address: '61 Katherine Street',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Sean Williams',
    decision_maker_title: 'Chief Operating Officer',
    decision_maker_email: 'sean.williams@barloworld.com',
    decision_maker_phone: '+27 11 445 1000',
    source_name: 'google',
    ai_confidence: 72,
    ai_reasoning: 'Large logistics provider with own equipment rental division. Could be both customer and competitor. Exploring partnerships for electric forklift supply.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['logistics', 'partnership-potential'],
  },
  {
    company_name: 'Distell Group',
    trading_name: 'Distell',
    industry: 'Food & Beverage',
    website: 'https://www.distell.co.za',
    company_size: '201-500',
    address: 'Aan-de-Wagenweg',
    city: 'Stellenbosch',
    province: 'Western Cape',
    country: 'South Africa',
    decision_maker_name: 'Francois Marais',
    decision_maker_title: 'Warehouse Operations Manager',
    decision_maker_email: 'francois.marais@distell.co.za',
    decision_maker_phone: '+27 21 809 7000',
    source_name: 'industry_directory',
    ai_confidence: 80,
    ai_reasoning: 'Spirits and wine producer with multiple bottling plants and DCs. Uses 25+ forklifts in bottling and warehousing. Current lease with competitor expiring mid-2026.',
    buy_probability: 9,
    qualification_status: 'qualified',
    tags: ['beverages', 'lease-expiry', 'wine-region'],
  },
  {
    company_name: 'Grindrod Logistics',
    trading_name: 'Grindrod',
    industry: 'Logistics',
    website: 'https://www.grindrod.com',
    company_size: '201-500',
    address: 'Grindrod Mews, 106 Margaret Mncadi Ave',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Sipho Nkosi',
    decision_maker_title: 'Port Operations Director',
    decision_maker_email: 'sipho.nkosi@grindrod.com',
    decision_maker_phone: '+27 31 304 1451',
    source_name: 'linkedin',
    ai_confidence: 88,
    ai_reasoning: 'Major port logistics operator in Durban. Requires heavy-duty forklifts for container handling. Fleet of 30+ reach stackers and forklifts. Government port expansion increasing demand.',
    buy_probability: 9,
    qualification_status: 'new',
    tags: ['port-logistics', 'heavy-duty', 'expansion'],
  },
  {
    company_name: 'Hulamin Limited',
    trading_name: 'Hulamin',
    industry: 'Manufacturing',
    website: 'https://www.hulamin.com',
    company_size: '201-500',
    address: 'Moses Mabhida Road',
    city: 'Pietermaritzburg',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Richard Sobahle',
    decision_maker_title: 'Plant Manager',
    decision_maker_email: 'richard.sobahle@hulamin.co.za',
    decision_maker_phone: '+27 33 395 6911',
    source_name: 'google',
    ai_confidence: 70,
    ai_reasoning: 'Largest aluminium semi-fabricator in Africa. Heavy coils require specialized material handling. Currently using older diesel fleet — opportunity for electric conversion.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['aluminium', 'heavy-loads', 'diesel-to-electric'],
  },
  {
    company_name: 'Massmart Holdings',
    trading_name: 'Makro / Game',
    industry: 'Retail',
    website: 'https://www.massmart.co.za',
    company_size: '500+',
    address: '16 Peltier Drive',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Linda Mthembu',
    decision_maker_title: 'Head of Supply Chain',
    decision_maker_email: 'linda.mthembu@massmart.co.za',
    decision_maker_phone: '+27 11 517 0000',
    source_name: 'trade_show',
    ai_confidence: 77,
    ai_reasoning: 'Operates Makro and Game stores with large-format warehouses. 100+ forklifts across distribution network. Walmart ownership driving efficiency improvements.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['retail', 'walmart', 'efficiency-drive'],
  },
  {
    company_name: 'Transnet Port Terminals',
    trading_name: 'TPT',
    industry: 'Logistics',
    website: 'https://www.transnet.net',
    company_size: '500+',
    address: 'Bayhead Road',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Bongani Zulu',
    decision_maker_title: 'Terminal Equipment Manager',
    decision_maker_email: 'bongani.zulu@transnet.net',
    decision_maker_phone: '+27 31 361 6111',
    source_name: 'industry_directory',
    ai_confidence: 65,
    ai_reasoning: 'State-owned port operator with massive equipment fleet. Procurement through government tender process. Long sales cycle but very large potential order volumes.',
    buy_probability: 6,
    qualification_status: 'new',
    tags: ['government', 'tender', 'port', 'high-volume'],
  },
  {
    company_name: 'Nampak Limited',
    trading_name: 'Nampak',
    industry: 'Manufacturing',
    website: 'https://www.nampak.com',
    company_size: '201-500',
    address: 'Hampton Park North',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Kobus van Zyl',
    decision_maker_title: 'Operations Manager',
    decision_maker_email: 'kobus.vanzyl@nampak.com',
    decision_maker_phone: '+27 11 719 6300',
    source_name: 'referral',
    ai_confidence: 73,
    ai_reasoning: 'Africa largest packaging company. Multiple production plants handling heavy reels and palletized goods. Restructuring operations — fleet consolidation opportunity.',
    buy_probability: 7,
    qualification_status: 'reviewing',
    tags: ['packaging', 'restructuring', 'consolidation'],
  },
  {
    company_name: 'PPC Cement',
    trading_name: 'PPC',
    industry: 'Construction',
    website: 'https://www.ppc.co.za',
    company_size: '201-500',
    address: '148 Katherine Street',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'David Gillmer',
    decision_maker_title: 'Plant Operations Director',
    decision_maker_email: 'david.gillmer@ppc.co.za',
    decision_maker_phone: '+27 11 386 9000',
    source_name: 'google',
    ai_confidence: 68,
    ai_reasoning: 'Major cement producer with heavy material handling at bagging plants. Dusty environment requires robust equipment. 8 plants across SA, each needing 3-5 forklifts.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['cement', 'harsh-environment', 'multi-plant'],
  },
  {
    company_name: 'Vector Logistics',
    trading_name: 'Vector',
    industry: 'Logistics',
    website: 'https://www.vectorlog.com',
    company_size: '51-200',
    address: '11 Jan Smuts Avenue',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Michelle Sobey',
    decision_maker_title: 'General Manager',
    decision_maker_email: 'michelle.sobey@vectorlog.com',
    decision_maker_phone: '+27 11 695 4000',
    source_name: 'linkedin',
    ai_confidence: 81,
    ai_reasoning: 'Cold chain specialist operating temperature-controlled warehouses. Electric forklifts mandatory for cold rooms. Currently evaluating new supplier for fleet of 15 units.',
    buy_probability: 9,
    qualification_status: 'qualified',
    tags: ['cold-chain', 'electric-mandatory', 'active-evaluation'],
  },
  {
    company_name: 'Coega Development Corporation',
    trading_name: 'Coega IDZ',
    industry: 'Construction',
    website: 'https://www.coega.co.za',
    company_size: '51-200',
    address: 'Corner Alcyon Road & Kosi Street',
    city: 'Port Elizabeth',
    province: 'Eastern Cape',
    country: 'South Africa',
    decision_maker_name: 'Ayanda Mzamo',
    decision_maker_title: 'Industrial Zone Manager',
    decision_maker_email: 'ayanda.mzamo@coega.co.za',
    decision_maker_phone: '+27 41 403 0400',
    source_name: 'trade_show',
    ai_confidence: 60,
    ai_reasoning: 'Industrial development zone attracting manufacturers. Multiple tenants need forklift equipment. Could serve as channel partner — referring tenants for forklift needs.',
    buy_probability: 6,
    qualification_status: 'new',
    tags: ['idz', 'channel-partner', 'eastern-cape'],
  },
  {
    company_name: 'Mondi Group SA',
    trading_name: 'Mondi',
    industry: 'Manufacturing',
    website: 'https://www.mondigroup.com',
    company_size: '500+',
    address: 'Mondi Drive',
    city: 'Richards Bay',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Peter Oswald',
    decision_maker_title: 'SA Operations Manager',
    decision_maker_email: 'peter.oswald@mondigroup.com',
    decision_maker_phone: '+27 35 902 2111',
    source_name: 'google',
    ai_confidence: 76,
    ai_reasoning: 'Global packaging and paper group with large Richards Bay mill. Heavy-duty material handling for timber and paper reels. Fleet of 20+ units due for replacement.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['paper', 'heavy-duty', 'fleet-replacement'],
  },
  {
    company_name: 'McCarthy Fleet Solutions',
    trading_name: 'McCarthy Fleet',
    industry: 'Automotive',
    website: 'https://www.mccarthyfleet.co.za',
    company_size: '201-500',
    address: '74 Rigger Road',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Werner Oberholzer',
    decision_maker_title: 'Fleet Division Head',
    decision_maker_email: 'werner.oberholzer@mccarthy.co.za',
    decision_maker_phone: '+27 11 321 6000',
    source_name: 'referral',
    ai_confidence: 55,
    ai_reasoning: 'Vehicle leasing company expanding into material handling equipment leasing. Partnership potential — they could lease our forklifts to their automotive client base.',
    buy_probability: 6,
    qualification_status: 'new',
    tags: ['automotive', 'partnership', 'leasing'],
  },
  {
    company_name: 'RCL Foods',
    trading_name: 'RCL',
    industry: 'Food & Beverage',
    website: 'https://www.rclfoods.com',
    company_size: '500+',
    address: '6 Cascade Crescent',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Jacques Roux',
    decision_maker_title: 'Warehouse Operations Manager',
    decision_maker_email: 'jacques.roux@rclfoods.com',
    decision_maker_phone: '+27 31 242 8600',
    source_name: 'linkedin',
    ai_confidence: 79,
    ai_reasoning: 'One of SA largest food producers (Rainbow Chicken, Selati Sugar). Multiple cold storage and dry warehouse facilities. 60+ forklifts across operations. Sugar division especially forklift-intensive.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['food', 'cold-chain', 'sugar', 'high-volume'],
  },
  {
    company_name: 'Mpact Limited',
    trading_name: 'Mpact',
    industry: 'Manufacturing',
    website: 'https://www.mpact.co.za',
    company_size: '201-500',
    address: '4th Floor, 3 Melrose Boulevard',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Bruce Strong',
    decision_maker_title: 'Recycling Operations Director',
    decision_maker_email: 'bruce.strong@mpact.co.za',
    decision_maker_phone: '+27 11 994 5500',
    source_name: 'google',
    ai_confidence: 71,
    ai_reasoning: 'Largest paper and plastic recycler in SA. 40+ recycling sites need material handling equipment. Growing rapidly due to Extended Producer Responsibility regulations.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['recycling', 'growing', 'epr-driven'],
  },
  {
    company_name: 'Sasol Mining',
    trading_name: 'Sasol',
    industry: 'Mining',
    website: 'https://www.sasol.com',
    company_size: '500+',
    address: '1 Sturdee Avenue',
    city: 'Secunda',
    province: 'Mpumalanga',
    country: 'South Africa',
    decision_maker_name: 'Hennie Venter',
    decision_maker_title: 'Mining Equipment Procurement Manager',
    decision_maker_email: 'hennie.venter@sasol.com',
    decision_maker_phone: '+27 17 610 0111',
    source_name: 'industry_directory',
    ai_confidence: 83,
    ai_reasoning: 'Major coal mining operation feeding Secunda CTL plant. Extensive warehouse and workshop operations requiring forklifts. Currently on competitor equipment with contracts under review.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['mining', 'coal', 'contract-review', 'mpumalanga'],
  },
  {
    company_name: 'Afgri Group',
    trading_name: 'Afgri',
    industry: 'Agriculture',
    website: 'https://www.afgri.co.za',
    company_size: '201-500',
    address: '12 Byls Bridge Boulevard',
    city: 'Centurion',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Carel Badenhorst',
    decision_maker_title: 'Grain Storage Operations Manager',
    decision_maker_email: 'carel.badenhorst@afgri.co.za',
    decision_maker_phone: '+27 12 663 9000',
    source_name: 'trade_show',
    ai_confidence: 66,
    ai_reasoning: 'Agricultural services company with grain silos and equipment dealerships across SA. Uses forklifts for grain bag handling and dealership operations. Seasonal peak demand.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['agriculture', 'grain', 'seasonal', 'dealership'],
  },
  {
    company_name: 'Ceramic Industries',
    trading_name: 'Betta Building Products',
    industry: 'Manufacturing',
    website: 'https://www.ceramic.co.za',
    company_size: '51-200',
    address: 'Vitro Building, Samrand Avenue',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Leon Erasmus',
    decision_maker_title: 'Production Manager',
    decision_maker_email: 'leon.erasmus@ceramic.co.za',
    decision_maker_phone: '+27 16 430 7200',
    source_name: 'google',
    ai_confidence: 64,
    ai_reasoning: 'Tile and sanitaryware manufacturer. Heavy palletized loads of ceramic tiles. Current fleet aging — 5 forklifts over 8 years old. Budget allocated for replacement in FY2027.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['ceramics', 'aging-fleet', 'budget-allocated'],
  },
  {
    company_name: 'Clover Industries',
    trading_name: 'Clover',
    industry: 'Food & Beverage',
    website: 'https://www.clover.co.za',
    company_size: '201-500',
    address: 'Constantia Kloof',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Gerrit van der Westhuizen',
    decision_maker_title: 'Cold Chain Logistics Manager',
    decision_maker_email: 'gerrit.vdw@clover.co.za',
    decision_maker_phone: '+27 11 762 7000',
    source_name: 'referral',
    ai_confidence: 84,
    ai_reasoning: 'Major dairy producer with extensive cold chain infrastructure. Electric forklifts required for all cold storage operations. Operates 35+ forklifts. Referred by existing BIS Edge customer.',
    buy_probability: 9,
    qualification_status: 'qualified',
    tags: ['dairy', 'cold-chain', 'referral', 'electric-required'],
  },
  {
    company_name: 'Consol Glass',
    trading_name: 'Consol',
    industry: 'Manufacturing',
    website: 'https://www.consol.co.za',
    company_size: '201-500',
    address: 'Consol Boulevard',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Mike Arnold',
    decision_maker_title: 'Warehouse Manager',
    decision_maker_email: 'mike.arnold@consol.co.za',
    decision_maker_phone: '+27 11 726 6000',
    source_name: 'linkedin',
    ai_confidence: 69,
    ai_reasoning: 'SA largest glass manufacturer. 4 manufacturing plants with 15+ forklifts each. Glass handling requires specialized clamp attachments. Evaluating total cost of ownership.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['glass', 'specialized-attachments', 'tco-evaluation'],
  },
  {
    company_name: 'Unitrans Supply Chain Solutions',
    trading_name: 'Unitrans',
    industry: 'Logistics',
    website: 'https://www.unitrans.co.za',
    company_size: '201-500',
    address: 'Stellenbosch Square',
    city: 'Stellenbosch',
    province: 'Western Cape',
    country: 'South Africa',
    decision_maker_name: 'Jan Gillmer',
    decision_maker_title: 'Chief Supply Chain Officer',
    decision_maker_email: 'jan.gillmer@unitrans.co.za',
    decision_maker_phone: '+27 21 809 0700',
    source_name: 'google',
    ai_confidence: 74,
    ai_reasoning: 'KWV-linked supply chain company managing warehouse operations for multiple FMCG brands. 50+ forklifts across client sites. Seeking single-supplier fleet solution.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['3pl', 'fmcg', 'single-supplier', 'western-cape'],
  },
  {
    company_name: 'Exxaro Resources',
    trading_name: 'Exxaro',
    industry: 'Mining',
    website: 'https://www.exxaro.com',
    company_size: '500+',
    address: 'Roger Dyason Road',
    city: 'Pretoria',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Mandla Ndlovu',
    decision_maker_title: 'Equipment Procurement Lead',
    decision_maker_email: 'mandla.ndlovu@exxaro.com',
    decision_maker_phone: '+27 12 307 5000',
    source_name: 'industry_directory',
    ai_confidence: 78,
    ai_reasoning: 'One of SA largest coal miners with operations in Limpopo and Mpumalanga. Workshop and warehouse operations at 6 mine sites. Committed to energy transition — interested in electric MHE.',
    buy_probability: 8,
    qualification_status: 'reviewing',
    tags: ['mining', 'coal', 'energy-transition', 'multi-site'],
  },
  {
    company_name: 'TWK Agri',
    trading_name: 'TWK',
    industry: 'Agriculture',
    website: 'https://www.twkagri.com',
    company_size: '51-200',
    address: '1 High Street',
    city: 'Piet Retief',
    province: 'Mpumalanga',
    country: 'South Africa',
    decision_maker_name: 'Pieter Bosman',
    decision_maker_title: 'Grain Division Manager',
    decision_maker_email: 'pieter.bosman@twkagri.com',
    decision_maker_phone: '+27 17 826 6000',
    source_name: 'trade_show',
    ai_confidence: 58,
    ai_reasoning: 'Agricultural cooperative with silos, mills, and retail outlets in Mpumalanga. Currently using mix of owned and rented forklifts. Looking to consolidate under single rental contract.',
    buy_probability: 6,
    qualification_status: 'new',
    tags: ['agriculture', 'cooperative', 'consolidation', 'mpumalanga'],
  },
  {
    company_name: 'ArcelorMittal South Africa',
    trading_name: 'AMSA',
    industry: 'Manufacturing',
    website: 'https://www.arcelormittalsa.com',
    company_size: '500+',
    address: 'Main Building, Delfos Boulevard',
    city: 'Vanderbijlpark',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Herman Steyn',
    decision_maker_title: 'Maintenance & Equipment Manager',
    decision_maker_email: 'herman.steyn@arcelormittal.com',
    decision_maker_phone: '+27 16 889 9111',
    source_name: 'industry_directory',
    ai_confidence: 70,
    ai_reasoning: 'SA largest steel producer with massive Vanderbijlpark and Saldanha works. Extremely heavy-duty environment. Currently owns fleet but exploring lease-to-own models for cost optimization.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['steel', 'heavy-duty', 'lease-to-own', 'enterprise'],
  },
];

async function seed() {
  console.log(`Seeding ${leads.length} leads...`);

  // Insert all leads
  const { data, error } = await supabase
    .from('leads')
    .insert(leads.map((lead) => ({
      ...lead,
      id: crypto.randomUUID(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })));

  if (error) {
    console.error('Error seeding leads:', error.message);
    process.exit(1);
  }

  console.log(`Successfully seeded ${leads.length} leads.`);
  console.log('Lead breakdown:');
  const byIndustry = {};
  const byProvince = {};
  const byStatus = {};
  leads.forEach((l) => {
    byIndustry[l.industry] = (byIndustry[l.industry] || 0) + 1;
    byProvince[l.province] = (byProvince[l.province] || 0) + 1;
    byStatus[l.qualification_status] = (byStatus[l.qualification_status] || 0) + 1;
  });
  console.log('  By Industry:', byIndustry);
  console.log('  By Province:', byProvince);
  console.log('  By Status:', byStatus);
}

seed();
