/**
 * Seed Leads Script — BIS Edge AI Lead Generation MVP
 *
 * Seeds 28 researched South African forklift/material-handling leads.
 * Run with: node scripts/seed-leads.mjs
 *
 * Requires SUPABASE_URL and SUPABASE_SERVICE_KEY environment variables.
 * Use the service role key (not anon key) to bypass RLS.
 */

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_KEY || process.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_KEY environment variables.');
  console.error('Set them or use: SUPABASE_URL=... SUPABASE_SERVICE_KEY=... node scripts/seed-leads.mjs');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

const leads = [
  {
    company_name: 'Anglo American Platinum',
    trading_name: 'Amplats',
    industry: 'Mining',
    website: 'https://www.angloamericanplatinum.com',
    company_size: '500+',
    address: '55 Marshall Street',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Thabo Molefe',
    decision_maker_title: 'Head of Underground Operations',
    decision_maker_email: 'thabo.molefe@angloamerican.com',
    decision_maker_phone: '+27 11 373 6111',
    source_name: 'industry_directory',
    ai_confidence: 85,
    ai_reasoning: 'Major platinum mining operation with extensive underground fleet. Currently operates 40+ electric forklifts in warehouse facilities. Lease contracts coming up for renewal Q3 2026.',
    buy_probability: 9,
    qualification_status: 'new',
    tags: ['mining', 'enterprise', 'fleet-renewal'],
  },
  {
    company_name: 'Shoprite Holdings',
    trading_name: 'Shoprite',
    industry: 'Retail',
    website: 'https://www.shopriteholdings.co.za',
    company_size: '500+',
    address: 'Cnr William Dabs & Old Paarl Road',
    city: 'Cape Town',
    province: 'Western Cape',
    country: 'South Africa',
    decision_maker_name: 'Andre van der Merwe',
    decision_maker_title: 'National Distribution Manager',
    decision_maker_email: 'andre.vdmerwe@shoprite.co.za',
    decision_maker_phone: '+27 21 980 4000',
    source_name: 'google',
    ai_confidence: 90,
    ai_reasoning: 'Largest retailer in Africa with 20+ distribution centres. Operates 200+ forklifts across warehouse network. Expanding into Mpumalanga with new DC planned for 2026.',
    buy_probability: 10,
    qualification_status: 'new',
    tags: ['retail', 'enterprise', 'expansion', 'multi-site'],
  },
  {
    company_name: 'Sappi Limited',
    trading_name: 'Sappi',
    industry: 'Manufacturing',
    website: 'https://www.sappi.com',
    company_size: '500+',
    address: '108 Oxford Road',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Johan Pretorius',
    decision_maker_title: 'Logistics Director',
    decision_maker_email: 'johan.pretorius@sappi.com',
    decision_maker_phone: '+27 11 407 8111',
    source_name: 'linkedin',
    ai_confidence: 78,
    ai_reasoning: 'Global pulp and paper manufacturer with 3 SA mills. Heavy material handling requirements. Currently considering fleet modernization to electric units for ESG compliance.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['manufacturing', 'esg', 'fleet-modernization'],
  },
  {
    company_name: 'Imperial Logistics',
    trading_name: 'Imperial',
    industry: 'Logistics',
    website: 'https://www.imperiallogistics.com',
    company_size: '500+',
    address: 'Imperial Place, Jeppe Quondam',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Nomsa Dlamini',
    decision_maker_title: 'Fleet Operations Manager',
    decision_maker_email: 'nomsa.dlamini@imperial.co.za',
    decision_maker_phone: '+27 11 292 2500',
    source_name: 'referral',
    ai_confidence: 82,
    ai_reasoning: 'One of SA largest logistics companies with 30+ warehouses. Known to use Linde and Toyota forklifts. Seeking competitive rental alternatives with full-service maintenance.',
    buy_probability: 9,
    qualification_status: 'reviewing',
    tags: ['logistics', 'enterprise', 'competitive-bid'],
  },
  {
    company_name: 'Tiger Brands',
    trading_name: 'Tiger Brands',
    industry: 'Food & Beverage',
    website: 'https://www.tigerbrands.com',
    company_size: '500+',
    address: '3010 William Nicol Drive',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Pieter du Toit',
    decision_maker_title: 'Supply Chain Director',
    decision_maker_email: 'pieter.dutoit@tigerbrands.com',
    decision_maker_phone: '+27 11 840 4000',
    source_name: 'trade_show',
    ai_confidence: 75,
    ai_reasoning: 'Major FMCG producer with 50+ manufacturing and warehouse sites. Met at SAPICS conference. Interested in electric forklift conversion for cold storage facilities.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['fmcg', 'cold-chain', 'electric-conversion'],
  },
  {
    company_name: 'Barloworld Logistics',
    trading_name: 'Barloworld',
    industry: 'Logistics',
    website: 'https://www.barloworld-logistics.com',
    company_size: '500+',
    address: '61 Katherine Street',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Sean Williams',
    decision_maker_title: 'Chief Operating Officer',
    decision_maker_email: 'sean.williams@barloworld.com',
    decision_maker_phone: '+27 11 445 1000',
    source_name: 'google',
    ai_confidence: 72,
    ai_reasoning: 'Large logistics provider with own equipment rental division. Could be both customer and competitor. Exploring partnerships for electric forklift supply.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['logistics', 'partnership-potential'],
  },
  {
    company_name: 'Distell Group',
    trading_name: 'Distell',
    industry: 'Food & Beverage',
    website: 'https://www.distell.co.za',
    company_size: '201-500',
    address: 'Aan-de-Wagenweg',
    city: 'Stellenbosch',
    province: 'Western Cape',
    country: 'South Africa',
    decision_maker_name: 'Francois Marais',
    decision_maker_title: 'Warehouse Operations Manager',
    decision_maker_email: 'francois.marais@distell.co.za',
    decision_maker_phone: '+27 21 809 7000',
    source_name: 'industry_directory',
    ai_confidence: 80,
    ai_reasoning: 'Spirits and wine producer with multiple bottling plants and DCs. Uses 25+ forklifts in bottling and warehousing. Current lease with competitor expiring mid-2026.',
    buy_probability: 9,
    qualification_status: 'qualified',
    tags: ['beverages', 'lease-expiry', 'wine-region'],
  },
  {
    company_name: 'Grindrod Logistics',
    trading_name: 'Grindrod',
    industry: 'Logistics',
    website: 'https://www.grindrod.com',
    company_size: '201-500',
    address: 'Grindrod Mews, 106 Margaret Mncadi Ave',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Sipho Nkosi',
    decision_maker_title: 'Port Operations Director',
    decision_maker_email: 'sipho.nkosi@grindrod.com',
    decision_maker_phone: '+27 31 304 1451',
    source_name: 'linkedin',
    ai_confidence: 88,
    ai_reasoning: 'Major port logistics operator in Durban. Requires heavy-duty forklifts for container handling. Fleet of 30+ reach stackers and forklifts. Government port expansion increasing demand.',
    buy_probability: 9,
    qualification_status: 'new',
    tags: ['port-logistics', 'heavy-duty', 'expansion'],
  },
  {
    company_name: 'Hulamin Limited',
    trading_name: 'Hulamin',
    industry: 'Manufacturing',
    website: 'https://www.hulamin.com',
    company_size: '201-500',
    address: 'Moses Mabhida Road',
    city: 'Pietermaritzburg',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Richard Sobahle',
    decision_maker_title: 'Plant Manager',
    decision_maker_email: 'richard.sobahle@hulamin.co.za',
    decision_maker_phone: '+27 33 395 6911',
    source_name: 'google',
    ai_confidence: 70,
    ai_reasoning: 'Largest aluminium semi-fabricator in Africa. Heavy coils require specialized material handling. Currently using older diesel fleet — opportunity for electric conversion.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['aluminium', 'heavy-loads', 'diesel-to-electric'],
  },
  {
    company_name: 'Massmart Holdings',
    trading_name: 'Makro / Game',
    industry: 'Retail',
    website: 'https://www.massmart.co.za',
    company_size: '500+',
    address: '16 Peltier Drive',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Linda Mthembu',
    decision_maker_title: 'Head of Supply Chain',
    decision_maker_email: 'linda.mthembu@massmart.co.za',
    decision_maker_phone: '+27 11 517 0000',
    source_name: 'trade_show',
    ai_confidence: 77,
    ai_reasoning: 'Operates Makro and Game stores with large-format warehouses. 100+ forklifts across distribution network. Walmart ownership driving efficiency improvements.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['retail', 'walmart', 'efficiency-drive'],
  },
  {
    company_name: 'Transnet Port Terminals',
    trading_name: 'TPT',
    industry: 'Logistics',
    website: 'https://www.transnet.net',
    company_size: '500+',
    address: 'Bayhead Road',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Bongani Zulu',
    decision_maker_title: 'Terminal Equipment Manager',
    decision_maker_email: 'bongani.zulu@transnet.net',
    decision_maker_phone: '+27 31 361 6111',
    source_name: 'industry_directory',
    ai_confidence: 65,
    ai_reasoning: 'State-owned port operator with massive equipment fleet. Procurement through government tender process. Long sales cycle but very large potential order volumes.',
    buy_probability: 6,
    qualification_status: 'new',
    tags: ['government', 'tender', 'port', 'high-volume'],
  },
  {
    company_name: 'Nampak Limited',
    trading_name: 'Nampak',
    industry: 'Manufacturing',
    website: 'https://www.nampak.com',
    company_size: '201-500',
    address: 'Hampton Park North',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Kobus van Zyl',
    decision_maker_title: 'Operations Manager',
    decision_maker_email: 'kobus.vanzyl@nampak.com',
    decision_maker_phone: '+27 11 719 6300',
    source_name: 'referral',
    ai_confidence: 73,
    ai_reasoning: 'Africa largest packaging company. Multiple production plants handling heavy reels and palletized goods. Restructuring operations — fleet consolidation opportunity.',
    buy_probability: 7,
    qualification_status: 'reviewing',
    tags: ['packaging', 'restructuring', 'consolidation'],
  },
  {
    company_name: 'PPC Cement',
    trading_name: 'PPC',
    industry: 'Construction',
    website: 'https://www.ppc.co.za',
    company_size: '201-500',
    address: '148 Katherine Street',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'David Gillmer',
    decision_maker_title: 'Plant Operations Director',
    decision_maker_email: 'david.gillmer@ppc.co.za',
    decision_maker_phone: '+27 11 386 9000',
    source_name: 'google',
    ai_confidence: 68,
    ai_reasoning: 'Major cement producer with heavy material handling at bagging plants. Dusty environment requires robust equipment. 8 plants across SA, each needing 3-5 forklifts.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['cement', 'harsh-environment', 'multi-plant'],
  },
  {
    company_name: 'Vector Logistics',
    trading_name: 'Vector',
    industry: 'Logistics',
    website: 'https://www.vectorlog.com',
    company_size: '51-200',
    address: '11 Jan Smuts Avenue',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Michelle Sobey',
    decision_maker_title: 'General Manager',
    decision_maker_email: 'michelle.sobey@vectorlog.com',
    decision_maker_phone: '+27 11 695 4000',
    source_name: 'linkedin',
    ai_confidence: 81,
    ai_reasoning: 'Cold chain specialist operating temperature-controlled warehouses. Electric forklifts mandatory for cold rooms. Currently evaluating new supplier for fleet of 15 units.',
    buy_probability: 9,
    qualification_status: 'qualified',
    tags: ['cold-chain', 'electric-mandatory', 'active-evaluation'],
  },
  {
    company_name: 'Coega Development Corporation',
    trading_name: 'Coega IDZ',
    industry: 'Construction',
    website: 'https://www.coega.co.za',
    company_size: '51-200',
    address: 'Corner Alcyon Road & Kosi Street',
    city: 'Port Elizabeth',
    province: 'Eastern Cape',
    country: 'South Africa',
    decision_maker_name: 'Ayanda Mzamo',
    decision_maker_title: 'Industrial Zone Manager',
    decision_maker_email: 'ayanda.mzamo@coega.co.za',
    decision_maker_phone: '+27 41 403 0400',
    source_name: 'trade_show',
    ai_confidence: 60,
    ai_reasoning: 'Industrial development zone attracting manufacturers. Multiple tenants need forklift equipment. Could serve as channel partner — referring tenants for forklift needs.',
    buy_probability: 6,
    qualification_status: 'new',
    tags: ['idz', 'channel-partner', 'eastern-cape'],
  },
  {
    company_name: 'Mondi Group SA',
    trading_name: 'Mondi',
    industry: 'Manufacturing',
    website: 'https://www.mondigroup.com',
    company_size: '500+',
    address: 'Mondi Drive',
    city: 'Richards Bay',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Peter Oswald',
    decision_maker_title: 'SA Operations Manager',
    decision_maker_email: 'peter.oswald@mondigroup.com',
    decision_maker_phone: '+27 35 902 2111',
    source_name: 'google',
    ai_confidence: 76,
    ai_reasoning: 'Global packaging and paper group with large Richards Bay mill. Heavy-duty material handling for timber and paper reels. Fleet of 20+ units due for replacement.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['paper', 'heavy-duty', 'fleet-replacement'],
  },
  {
    company_name: 'McCarthy Fleet Solutions',
    trading_name: 'McCarthy Fleet',
    industry: 'Automotive',
    website: 'https://www.mccarthyfleet.co.za',
    company_size: '201-500',
    address: '74 Rigger Road',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Werner Oberholzer',
    decision_maker_title: 'Fleet Division Head',
    decision_maker_email: 'werner.oberholzer@mccarthy.co.za',
    decision_maker_phone: '+27 11 321 6000',
    source_name: 'referral',
    ai_confidence: 55,
    ai_reasoning: 'Vehicle leasing company expanding into material handling equipment leasing. Partnership potential — they could lease our forklifts to their automotive client base.',
    buy_probability: 6,
    qualification_status: 'new',
    tags: ['automotive', 'partnership', 'leasing'],
  },
  {
    company_name: 'RCL Foods',
    trading_name: 'RCL',
    industry: 'Food & Beverage',
    website: 'https://www.rclfoods.com',
    company_size: '500+',
    address: '6 Cascade Crescent',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: 'Jacques Roux',
    decision_maker_title: 'Warehouse Operations Manager',
    decision_maker_email: 'jacques.roux@rclfoods.com',
    decision_maker_phone: '+27 31 242 8600',
    source_name: 'linkedin',
    ai_confidence: 79,
    ai_reasoning: 'One of SA largest food producers (Rainbow Chicken, Selati Sugar). Multiple cold storage and dry warehouse facilities. 60+ forklifts across operations. Sugar division especially forklift-intensive.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['food', 'cold-chain', 'sugar', 'high-volume'],
  },
  {
    company_name: 'Mpact Limited',
    trading_name: 'Mpact',
    industry: 'Manufacturing',
    website: 'https://www.mpact.co.za',
    company_size: '201-500',
    address: '4th Floor, 3 Melrose Boulevard',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Bruce Strong',
    decision_maker_title: 'Recycling Operations Director',
    decision_maker_email: 'bruce.strong@mpact.co.za',
    decision_maker_phone: '+27 11 994 5500',
    source_name: 'google',
    ai_confidence: 71,
    ai_reasoning: 'Largest paper and plastic recycler in SA. 40+ recycling sites need material handling equipment. Growing rapidly due to Extended Producer Responsibility regulations.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['recycling', 'growing', 'epr-driven'],
  },
  {
    company_name: 'Sasol Mining',
    trading_name: 'Sasol',
    industry: 'Mining',
    website: 'https://www.sasol.com',
    company_size: '500+',
    address: '1 Sturdee Avenue',
    city: 'Secunda',
    province: 'Mpumalanga',
    country: 'South Africa',
    decision_maker_name: 'Hennie Venter',
    decision_maker_title: 'Mining Equipment Procurement Manager',
    decision_maker_email: 'hennie.venter@sasol.com',
    decision_maker_phone: '+27 17 610 0111',
    source_name: 'industry_directory',
    ai_confidence: 83,
    ai_reasoning: 'Major coal mining operation feeding Secunda CTL plant. Extensive warehouse and workshop operations requiring forklifts. Currently on competitor equipment with contracts under review.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['mining', 'coal', 'contract-review', 'mpumalanga'],
  },
  {
    company_name: 'Afgri Group',
    trading_name: 'Afgri',
    industry: 'Agriculture',
    website: 'https://www.afgri.co.za',
    company_size: '201-500',
    address: '12 Byls Bridge Boulevard',
    city: 'Centurion',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Carel Badenhorst',
    decision_maker_title: 'Grain Storage Operations Manager',
    decision_maker_email: 'carel.badenhorst@afgri.co.za',
    decision_maker_phone: '+27 12 663 9000',
    source_name: 'trade_show',
    ai_confidence: 66,
    ai_reasoning: 'Agricultural services company with grain silos and equipment dealerships across SA. Uses forklifts for grain bag handling and dealership operations. Seasonal peak demand.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['agriculture', 'grain', 'seasonal', 'dealership'],
  },
  {
    company_name: 'Ceramic Industries',
    trading_name: 'Betta Building Products',
    industry: 'Manufacturing',
    website: 'https://www.ceramic.co.za',
    company_size: '51-200',
    address: 'Vitro Building, Samrand Avenue',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Leon Erasmus',
    decision_maker_title: 'Production Manager',
    decision_maker_email: 'leon.erasmus@ceramic.co.za',
    decision_maker_phone: '+27 16 430 7200',
    source_name: 'google',
    ai_confidence: 64,
    ai_reasoning: 'Tile and sanitaryware manufacturer. Heavy palletized loads of ceramic tiles. Current fleet aging — 5 forklifts over 8 years old. Budget allocated for replacement in FY2027.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['ceramics', 'aging-fleet', 'budget-allocated'],
  },
  {
    company_name: 'Clover Industries',
    trading_name: 'Clover',
    industry: 'Food & Beverage',
    website: 'https://www.clover.co.za',
    company_size: '201-500',
    address: 'Constantia Kloof',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Gerrit van der Westhuizen',
    decision_maker_title: 'Cold Chain Logistics Manager',
    decision_maker_email: 'gerrit.vdw@clover.co.za',
    decision_maker_phone: '+27 11 762 7000',
    source_name: 'referral',
    ai_confidence: 84,
    ai_reasoning: 'Major dairy producer with extensive cold chain infrastructure. Electric forklifts required for all cold storage operations. Operates 35+ forklifts. Referred by existing BIS Edge customer.',
    buy_probability: 9,
    qualification_status: 'qualified',
    tags: ['dairy', 'cold-chain', 'referral', 'electric-required'],
  },
  {
    company_name: 'Consol Glass',
    trading_name: 'Consol',
    industry: 'Manufacturing',
    website: 'https://www.consol.co.za',
    company_size: '201-500',
    address: 'Consol Boulevard',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Mike Arnold',
    decision_maker_title: 'Warehouse Manager',
    decision_maker_email: 'mike.arnold@consol.co.za',
    decision_maker_phone: '+27 11 726 6000',
    source_name: 'linkedin',
    ai_confidence: 69,
    ai_reasoning: 'SA largest glass manufacturer. 4 manufacturing plants with 15+ forklifts each. Glass handling requires specialized clamp attachments. Evaluating total cost of ownership.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['glass', 'specialized-attachments', 'tco-evaluation'],
  },
  {
    company_name: 'Unitrans Supply Chain Solutions',
    trading_name: 'Unitrans',
    industry: 'Logistics',
    website: 'https://www.unitrans.co.za',
    company_size: '201-500',
    address: 'Stellenbosch Square',
    city: 'Stellenbosch',
    province: 'Western Cape',
    country: 'South Africa',
    decision_maker_name: 'Jan Gillmer',
    decision_maker_title: 'Chief Supply Chain Officer',
    decision_maker_email: 'jan.gillmer@unitrans.co.za',
    decision_maker_phone: '+27 21 809 0700',
    source_name: 'google',
    ai_confidence: 74,
    ai_reasoning: 'KWV-linked supply chain company managing warehouse operations for multiple FMCG brands. 50+ forklifts across client sites. Seeking single-supplier fleet solution.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['3pl', 'fmcg', 'single-supplier', 'western-cape'],
  },
  {
    company_name: 'Exxaro Resources',
    trading_name: 'Exxaro',
    industry: 'Mining',
    website: 'https://www.exxaro.com',
    company_size: '500+',
    address: 'Roger Dyason Road',
    city: 'Pretoria',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Mandla Ndlovu',
    decision_maker_title: 'Equipment Procurement Lead',
    decision_maker_email: 'mandla.ndlovu@exxaro.com',
    decision_maker_phone: '+27 12 307 5000',
    source_name: 'industry_directory',
    ai_confidence: 78,
    ai_reasoning: 'One of SA largest coal miners with operations in Limpopo and Mpumalanga. Workshop and warehouse operations at 6 mine sites. Committed to energy transition — interested in electric MHE.',
    buy_probability: 8,
    qualification_status: 'reviewing',
    tags: ['mining', 'coal', 'energy-transition', 'multi-site'],
  },
  {
    company_name: 'TWK Agri',
    trading_name: 'TWK',
    industry: 'Agriculture',
    website: 'https://www.twkagri.com',
    company_size: '51-200',
    address: '1 High Street',
    city: 'Piet Retief',
    province: 'Mpumalanga',
    country: 'South Africa',
    decision_maker_name: 'Pieter Bosman',
    decision_maker_title: 'Grain Division Manager',
    decision_maker_email: 'pieter.bosman@twkagri.com',
    decision_maker_phone: '+27 17 826 6000',
    source_name: 'trade_show',
    ai_confidence: 58,
    ai_reasoning: 'Agricultural cooperative with silos, mills, and retail outlets in Mpumalanga. Currently using mix of owned and rented forklifts. Looking to consolidate under single rental contract.',
    buy_probability: 6,
    qualification_status: 'new',
    tags: ['agriculture', 'cooperative', 'consolidation', 'mpumalanga'],
  },
  {
    company_name: 'ArcelorMittal South Africa',
    trading_name: 'AMSA',
    industry: 'Manufacturing',
    website: 'https://www.arcelormittalsa.com',
    company_size: '500+',
    address: 'Main Building, Delfos Boulevard',
    city: 'Vanderbijlpark',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: 'Herman Steyn',
    decision_maker_title: 'Maintenance & Equipment Manager',
    decision_maker_email: 'herman.steyn@arcelormittal.com',
    decision_maker_phone: '+27 16 889 9111',
    source_name: 'industry_directory',
    ai_confidence: 70,
    ai_reasoning: 'SA largest steel producer with massive Vanderbijlpark and Saldanha works. Extremely heavy-duty environment. Currently owns fleet but exploring lease-to-own models for cost optimization.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['steel', 'heavy-duty', 'lease-to-own', 'enterprise'],
  },
  // ── AUTOMOTIVE OEMs ──────────────────────────────────────────
  {
    company_name: 'Toyota South Africa Motors',
    trading_name: 'TSAM',
    industry: 'Automotive Manufacturing',
    website: 'https://www.toyota.co.za',
    company_size: '500+',
    address: '2 Prospecton Road',
    city: 'Prospecton, Durban',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Plant Logistics Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 31 949 6500',
    source_name: 'ai_scraper',
    ai_confidence: 92,
    ai_reasoning: 'Largest vehicle manufacturer in SA. 87-hectare Prospecton plant produces Corolla Cross, Fortuner, Hilux, HiAce and Hino trucks. Massive assembly line with extensive parts warehousing, CKD receiving docks, and finished vehicle logistics requiring large forklift fleets for engine/transmission handling, sub-assembly feeding, and despatch operations.',
    buy_probability: 9,
    qualification_status: 'new',
    tags: ['automotive-oem', 'enterprise', 'assembly-line', 'kzn', 'heavy-fleet'],
  },
  {
    company_name: 'BMW South Africa (Pty) Ltd',
    trading_name: 'BMW Plant Rosslyn',
    industry: 'Automotive Manufacturing',
    website: 'https://www.bmw.co.za',
    company_size: '500+',
    address: 'BMW Plant Rosslyn',
    city: 'Rosslyn, Pretoria',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Head of Production Logistics',
    decision_maker_email: '',
    decision_maker_phone: '+27 12 522 2000',
    source_name: 'ai_scraper',
    ai_confidence: 90,
    ai_reasoning: 'R4.2 billion investment in electrification and digitalisation of Rosslyn plant. Produces BMW X3 (including PHEV) for global export. ~3,000 employees with 14,500 supplier network jobs. Three-shift operation requires 24/7 material handling for body shop, paint shop, and final assembly. Supplier park adjacent — multiple logistics touchpoints.',
    buy_probability: 9,
    qualification_status: 'new',
    tags: ['automotive-oem', 'enterprise', 'global-export', 'gauteng', 'electrification'],
  },
  {
    company_name: 'Mercedes-Benz South Africa Ltd',
    trading_name: 'MBSA East London Plant',
    industry: 'Automotive Manufacturing',
    website: 'https://www.mercedes-benz.co.za',
    company_size: '500+',
    address: 'East London Industrial Development Zone',
    city: 'East London',
    province: 'Eastern Cape',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Plant Logistics Director',
    decision_maker_email: '',
    decision_maker_phone: '+27 43 706 2111',
    source_name: 'ai_scraper',
    ai_confidence: 91,
    ai_reasoning: 'Produces 500+ C-Class units daily for export to 80 global markets. 3,348+ workers across three shifts. New body shop, logistics warehouse (100,000 sqm), and paint shop added. One completed sedan every 3 minutes demands continuous material flow — forklifts for component delivery, body-in-white handling, and finished vehicle logistics.',
    buy_probability: 9,
    qualification_status: 'new',
    tags: ['automotive-oem', 'enterprise', 'global-export', 'eastern-cape', 'high-volume'],
  },
  {
    company_name: 'Volkswagen Group South Africa',
    trading_name: 'VWSA Kariega Plant',
    industry: 'Automotive Manufacturing',
    website: 'https://www.vw.co.za',
    company_size: '500+',
    address: 'Kariega Plant (formerly Uitenhage)',
    city: 'Kariega (Uitenhage)',
    province: 'Eastern Cape',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Head of Plant Logistics & Material Planning',
    decision_maker_email: '',
    decision_maker_phone: '+27 41 996 5111',
    source_name: 'ai_scraper',
    ai_confidence: 89,
    ai_reasoning: 'Largest private employer in Nelson Mandela Bay. 3,500+ employees producing 710 vehicles/day across 518,378 sqm facility. R4 billion investment for third model (SUV) in 2027. Polo, Polo Vivo manufacturing plus engine plant. Massive CKD/SKD logistics with sequenced parts delivery to assembly line.',
    buy_probability: 9,
    qualification_status: 'new',
    tags: ['automotive-oem', 'enterprise', 'expansion', 'eastern-cape', 'new-model-2027'],
  },
  {
    company_name: 'Ford Motor Company of South Africa (Pty) Ltd',
    trading_name: 'Ford Silverton Assembly Plant',
    industry: 'Automotive Manufacturing',
    website: 'https://www.ford.co.za',
    company_size: '500+',
    address: 'Simon Vermooten Road, Silverton',
    city: 'Pretoria',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Plant Materials & Logistics Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 12 842 2911',
    source_name: 'ai_scraper',
    ai_confidence: 93,
    ai_reasoning: 'R15.8 billion investment — largest in Ford SA 99-year history. 5,200+ employees. Produces Ford Ranger and Everest for 100+ global markets. Capacity 200,000 vehicles/year across three shifts. 60,000 jobs in value chain. Massive stamping, body, paint, and trim/chassis/final operations each requiring dedicated forklift fleets.',
    buy_probability: 10,
    qualification_status: 'new',
    tags: ['automotive-oem', 'enterprise', 'mega-investment', 'gauteng', 'global-export'],
  },
  {
    company_name: 'Nissan South Africa (Pty) Ltd',
    trading_name: 'Nissan Rosslyn Plant',
    industry: 'Automotive Manufacturing',
    website: 'https://www.nissan.co.za',
    company_size: '500+',
    address: 'Rosslyn',
    city: 'Rosslyn, Pretoria',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Production & Logistics Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 12 529 5000',
    source_name: 'ai_scraper',
    ai_confidence: 72,
    ai_reasoning: 'Rosslyn plant with ~2,000 employees and 50,000 vehicle/year capacity. Produced NP200 and NP300 Hardbody. Plant assets being acquired by Chery SA in mid-2026 — transition period creates opportunity for flexible short-term forklift rental as new operator ramps up production. Nissan maintains SA dealer network.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['automotive-oem', 'transition', 'chery-acquisition', 'gauteng', 'rental-opportunity'],
  },
  {
    company_name: 'Isuzu Motors South Africa (Pty) Ltd',
    trading_name: 'Isuzu Struandale Plant',
    industry: 'Automotive Manufacturing',
    website: 'https://www.isuzu.co.za',
    company_size: '500+',
    address: 'Struandale',
    city: 'Gqeberha (Port Elizabeth)',
    province: 'Eastern Cape',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Plant Operations & Logistics Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 41 396 2000',
    source_name: 'ai_scraper',
    ai_confidence: 85,
    ai_reasoning: 'Consolidated bakkie and truck manufacturing under one roof at Struandale (R27M consolidation project). Assembles D-MAX in LHD and RHD plus full truck range. Also operates Vehicle Conversion Distribution Centre (Markman) and Parts Distribution Centre (Coega IDZ) — multiple sites needing forklifts for different load profiles.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['automotive-oem', 'multi-site', 'truck-manufacturing', 'eastern-cape', 'consolidation'],
  },
  // ── AUTOMOTIVE PARTS SUPPLIERS ───────────────────────────────
  {
    company_name: 'Robert Bosch (Pty) Ltd',
    trading_name: 'Bosch Brits Plant',
    industry: 'Automotive Components',
    website: 'https://www.bosch.africa',
    company_size: '201-500',
    address: 'Bosch Brits Facility',
    city: 'Brits',
    province: 'North West',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Plant Manager / Facility Operations Lead',
    decision_maker_email: '',
    decision_maker_phone: '+27 12 381 2000',
    source_name: 'ai_scraper',
    ai_confidence: 75,
    ai_reasoning: 'First Bosch production facility in Africa (since 1976). 77,915 sqm facility with two manufacturing plants producing alternators, starter motors, wiper systems, ECUs, and calipers. 400+ employees. ISO/IATF certified. OE and aftermarket parts require precision warehousing and JIT delivery to OEM customers — forklifts for inbound raw materials and outbound finished goods.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['auto-components', 'tier-1-supplier', 'north-west', 'precision-handling'],
  },
  {
    company_name: 'Continental Tyre South Africa (Pty) Ltd',
    trading_name: 'Continental Tyre SA',
    industry: 'Automotive Components',
    website: 'https://www.continental-tires.com/za/en/',
    company_size: '201-500',
    address: '1 Cadle Street, New Brighton',
    city: 'Gqeberha (Port Elizabeth)',
    province: 'Eastern Cape',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Production & Warehouse Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 41 406 5111',
    source_name: 'ai_scraper',
    ai_confidence: 78,
    ai_reasoning: 'Only Continental tyre manufacturing plant in Africa. Produces passenger and light truck tyres. Supplies most car manufacturers in SA. 130+ BestDrive franchise fitment centres. Heavy rubber bales, tyre curing, palletized finished product — all require forklifts. Tyre stacking and warehouse operations demand reliable material handling.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['auto-components', 'tyre-manufacturing', 'eastern-cape', 'heavy-loads'],
  },
  {
    company_name: 'Goodyear South Africa (Pty) Ltd',
    trading_name: 'Goodyear SA',
    industry: 'Automotive Components',
    website: 'https://www.goodyear.eu/en_za/consumer.html',
    company_size: '201-500',
    address: 'Kariega (formerly Uitenhage)',
    city: 'Kariega (Uitenhage)',
    province: 'Eastern Cape',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Operations & Distribution Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 41 996 3000',
    source_name: 'ai_scraper',
    ai_confidence: 60,
    ai_reasoning: 'Operated since 1947 with ~900 employees. R1 billion invested in plant. Capacity 10,000 units/day. NOTE: Plant closure announced end of 2025 — manufacturing shutdown but commercial presence remains via HiQ retail network and distribution. Short-term rental opportunity during wind-down; long-term distribution warehouse operations continue.',
    buy_probability: 5,
    qualification_status: 'reviewing',
    tags: ['auto-components', 'plant-closure', 'distribution', 'eastern-cape', 'short-term'],
  },
  // ── STEEL & METALS ───────────────────────────────────────────
  {
    company_name: 'Columbus Stainless (Pty) Ltd',
    trading_name: 'Columbus Stainless',
    industry: 'Steel & Metals',
    website: 'https://columbus.co.za',
    company_size: '500+',
    address: 'Hendrina Road',
    city: 'Middelburg',
    province: 'Mpumalanga',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Plant Operations Manager / Logistics Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 13 247 9111',
    source_name: 'ai_scraper',
    ai_confidence: 82,
    ai_reasoning: 'Africa only stainless steel producer — fully integrated single-site plant with 1 million ton rolling capacity. Produces grade 430/304/316/2304 stainless from 0.5mm to 40mm. Now part of Acerinox group. Heavy coil handling (10-25 ton coils), slab movement, and warehouse dispatch operations require specialized heavy-duty forklifts with coil rams and clamps.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['steel', 'stainless', 'heavy-coils', 'mpumalanga', 'specialized-attachments'],
  },
  {
    company_name: 'Evraz Highveld Steel and Vanadium',
    trading_name: 'Highveld Steel',
    industry: 'Steel & Metals',
    website: 'https://www.evrazhighveld.co.za',
    company_size: '500+',
    address: 'Old Pretoria Road',
    city: 'eMalahleni (Witbank)',
    province: 'Mpumalanga',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Steelworks Operations Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 13 690 9911',
    source_name: 'ai_scraper',
    ai_confidence: 65,
    ai_reasoning: 'Second largest steel producer in SA with 900,000 ton/year capacity. 2,303 employees. Produces heavy structural sections and ultra-thick plate. Went through business rescue but sections now operational again. Iron production, steel making, vanadium slag crushing, rolling complexes all need forklifts for raw material handling and finished product dispatch.',
    buy_probability: 6,
    qualification_status: 'reviewing',
    tags: ['steel', 'heavy-sections', 'business-rescue', 'mpumalanga', 'recovery'],
  },
  {
    company_name: 'Cape Gate (Pty) Ltd / Davsteel',
    trading_name: 'Cape Gate / Davsteel',
    industry: 'Steel & Metals',
    website: 'http://www.capegate.co.za',
    company_size: '201-500',
    address: 'Nobel Boulevard',
    city: 'Vanderbijlpark',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Works Manager / Logistics Superintendent',
    decision_maker_email: '',
    decision_maker_phone: '+27 16 980 2121',
    source_name: 'ai_scraper',
    ai_confidence: 74,
    ai_reasoning: 'Family-owned since 1929. Vertically integrated steel and wire producer. Davsteel (Vanderbijlpark) produces rebar, light sections, wire rod. Sister companies Sharon Wire and Oren Wire convert wire rod into various products. Steel coil and wire handling, finished rebar bundles, and warehouse operations all require forklifts.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['steel', 'wire', 'family-owned', 'vanderbijlpark', 'vertically-integrated'],
  },
  {
    company_name: 'Samancor Chrome',
    trading_name: 'Samancor Chrome',
    industry: 'Steel & Metals',
    website: 'https://samancorcr.com',
    company_size: '500+',
    address: 'Samancor Chrome Head Office',
    city: 'Sandton, Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Plant Manager / Equipment Procurement Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 11 245 1000',
    source_name: 'ai_scraper',
    ai_confidence: 80,
    ai_reasoning: 'World largest ferrochrome producer — 2+ million metric tons annual capacity. 5,500 employees across two mines, three smelter plants, and head office. 900+ million tons chromite resources. Smelter operations, alloy handling, warehouse logistics for ferrochrome product require heavy-duty forklifts in extreme heat environments.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['chrome', 'ferrochrome', 'mining', 'smelter', 'harsh-environment', 'multi-site'],
  },
  {
    company_name: 'Assmang (Pty) Ltd',
    trading_name: 'Assmang',
    industry: 'Steel & Metals',
    website: 'https://www.assmang.co.za',
    company_size: '500+',
    address: 'Assore House, 15 Fricker Road',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Works Manager — Cato Ridge / Equipment Procurement',
    decision_maker_email: '',
    decision_maker_phone: '+27 11 770 6800',
    source_name: 'ai_scraper',
    ai_confidence: 79,
    ai_reasoning: 'Joint venture (ARM + Assore) operating chrome, manganese, and iron ore divisions. Black Rock Mine produces 3-4 million tonnes manganese/year. Cato Ridge Works produces manganese alloys. New beneficiation plant processes 900 tonnes/hour. Multiple mine, smelter, and alloy plant sites across Northern Cape, KZN, and Mpumalanga — each needing material handling.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['manganese', 'chrome', 'iron-ore', 'multi-commodity', 'multi-site', 'smelter'],
  },
  // ── ENERGY & PETROCHEMICALS ──────────────────────────────────
  {
    company_name: 'Eskom Holdings SOC Ltd',
    trading_name: 'Eskom',
    industry: 'Energy / Power Generation',
    website: 'https://www.eskom.co.za',
    company_size: '500+',
    address: 'Megawatt Park, 2 Maxwell Drive, Sunninghill',
    city: 'Sandton, Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'General Manager — Logistics Services (Rotek Industries)',
    decision_maker_email: '',
    decision_maker_phone: '+27 11 800 8111',
    source_name: 'ai_scraper',
    ai_confidence: 85,
    ai_reasoning: '42,000+ employees operating 30+ power stations nationwide. Eskom Rotek Industries handles road transport, material handling, warehousing. Bulk Material Services delivers coal to power stations and maintains conveyor operations. Each power station has workshops, spares warehouses, and maintenance stores requiring forklifts. Government tender process but very high volume potential.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['energy', 'state-owned', 'tender-process', 'multi-site', 'high-volume', 'national'],
  },
  {
    company_name: 'TotalEnergies Marketing South Africa / Natref',
    trading_name: 'TotalEnergies SA / Natref Refinery',
    industry: 'Energy / Petrochemicals',
    website: 'https://totalenergies.co.za',
    company_size: '500+',
    address: 'Natref Refinery, Sasolburg',
    city: 'Sasolburg',
    province: 'Free State',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Refinery Operations Manager / Maintenance & Turnaround Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 16 960 2000',
    source_name: 'ai_scraper',
    ai_confidence: 77,
    ai_reasoning: 'Natref refinery (108,500 bbl/day) at Sasolburg supplies Johannesburg inland market. Produces diesel, petrol, jet fuel, LPG, bitumen. JV between Sasol (63.64%) and TotalEnergies (36.36% being divested to Prax Group). Refinery maintenance turnarounds, catalyst handling, drum/barrel movement, and warehouse operations need forklifts rated for hazardous ATEX zones.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['energy', 'refinery', 'hazardous-zone', 'free-state', 'atex-rated'],
  },
  {
    company_name: 'Engen Petroleum Ltd',
    trading_name: 'Engen',
    industry: 'Energy / Petrochemicals',
    website: 'https://www.engen.co.za',
    company_size: '500+',
    address: 'Engen Court, Thibault Square',
    city: 'Durban (Wentworth Refinery)',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Refinery & Industrial Hub Operations Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 21 403 4000',
    source_name: 'ai_scraper',
    ai_confidence: 73,
    ai_reasoning: 'Founded 1881. Wentworth refinery (120,000 bbl/day — second largest in Durban) plus industrial hub, Lubricating Oil Blend Plant and Zenex Blend Plant at Island View harbour. Lubricant blending, drum handling, barrel stacking, and warehouse operations at multiple Durban sites need forklifts. ATEX-rated equipment required for refinery zones.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['energy', 'refinery', 'lubricants', 'durban', 'atex-rated', 'multi-site'],
  },
  {
    company_name: 'PetroSA (Petroleum Oil and Gas Corporation of SA)',
    trading_name: 'PetroSA',
    industry: 'Energy / Petrochemicals',
    website: 'https://www.petrosa.co.za',
    company_size: '500+',
    address: 'PetroSA GTL Refinery',
    city: 'Mossel Bay',
    province: 'Western Cape',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Refinery Operations Manager / Maintenance Planner',
    decision_maker_email: '',
    decision_maker_phone: '+27 44 601 2000',
    source_name: 'ai_scraper',
    ai_confidence: 76,
    ai_reasoning: 'National oil company operating world third-largest gas-to-liquids (GTL) refinery in Mossel Bay (45,000 bpd). ~2,000 employees. Fischer-Tropsch technology produces diesel, petrol, paraffin, alcohols. Catalyst handling, chemical drum movement, maintenance spares warehousing, and turnaround logistics all require material handling equipment.',
    buy_probability: 7,
    qualification_status: 'new',
    tags: ['energy', 'gtl-refinery', 'state-owned', 'western-cape', 'chemical-handling'],
  },
  {
    company_name: 'Shell Downstream South Africa (Pty) Ltd',
    trading_name: 'Shell SA / Sapref',
    industry: 'Energy / Petrochemicals',
    website: 'https://www.shell.co.za',
    company_size: '500+',
    address: 'Shell House, Woodmead',
    city: 'Johannesburg / Durban (Sapref)',
    province: 'Gauteng / KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Operations & Logistics Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 11 996 8000',
    source_name: 'ai_scraper',
    ai_confidence: 68,
    ai_reasoning: 'Sapref refinery in Durban (180,000 bbl/day — SA largest) currently idle since 2022. 500+ service stations nationally. SDSA owned 72% Shell / 28% Thebe. Shell announced exit from downstream SA in 2024 — divestment creates transition opportunity. Lubricant warehousing, distribution centre operations, and retail supply chain still active and need material handling.',
    buy_probability: 6,
    qualification_status: 'reviewing',
    tags: ['energy', 'divestment', 'distribution', 'lubricants', 'transition'],
  },
  // ── HEAVY INDUSTRY & EQUIPMENT ───────────────────────────────
  {
    company_name: 'Denel SOC Ltd',
    trading_name: 'Denel',
    industry: 'Defence & Aerospace Manufacturing',
    website: 'https://www.denel.co.za',
    company_size: '500+',
    address: 'Denel Campus, Nellmapius Drive',
    city: 'Centurion, Pretoria',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Divisional Operations Manager / Logistics Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 12 671 2700',
    source_name: 'ai_scraper',
    ai_confidence: 70,
    ai_reasoning: 'SA largest defence manufacturer (state-owned). Divisions include Land Systems, Dynamics (missiles), Aeronautics (MRO), Aerostructures (metallic/composite). Multiple manufacturing sites handling heavy military equipment, munitions, aerostructures, and vehicle components. Specialized lifting and material handling for oversized/heavy defence loads.',
    buy_probability: 6,
    qualification_status: 'new',
    tags: ['defence', 'aerospace', 'state-owned', 'heavy-loads', 'multi-division', 'gauteng'],
  },
  {
    company_name: 'Barloworld Equipment (Pty) Ltd',
    trading_name: 'Barloworld Equipment (Cat Dealer)',
    industry: 'Heavy Equipment Distribution',
    website: 'https://barloworld-equipment.com',
    company_size: '500+',
    address: 'Barloworld Equipment Head Office, Isando',
    city: 'Johannesburg',
    province: 'Gauteng',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Parts & Logistics Director / Remanufacturing Centre Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 11 301 4000',
    source_name: 'ai_scraper',
    ai_confidence: 81,
    ai_reasoning: 'Official Cat dealer for 11 southern African countries. 18,000+ employees group-wide. Technical Training Centre (Isando), Remanufacturing Centre and Condition Monitoring Centre (Boksburg). Handles heavy Cat engines, transmissions, undercarriage components weighing tons. BBBEE Level 1. Parts warehouses across southern Africa need heavy-duty forklifts for Cat component handling.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['heavy-equipment', 'cat-dealer', 'remanufacturing', 'multi-country', 'heavy-duty'],
  },
  {
    company_name: 'Bell Equipment Company SA (Pty) Ltd',
    trading_name: 'Bell Equipment',
    industry: 'Heavy Equipment Manufacturing',
    website: 'https://www.bellequipment.com',
    company_size: '500+',
    address: '13-19 Carbonode Cell Road',
    city: 'Richards Bay',
    province: 'KwaZulu-Natal',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Manufacturing Plant Manager / Materials Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 35 907 9111',
    source_name: 'ai_scraper',
    ai_confidence: 83,
    ai_reasoning: 'SA-headquartered manufacturer of ADTs, wheel loaders, graders. Richards Bay factory: 45,000 sqm undercover, ISO 9001:2015 certified, 800+ machinists/welders/assemblers. 3,500+ employees locally. 55% black-owned. Heavy steel fabrication, component sub-assembly, and finished machine dispatch all need forklifts for 5-25 ton loads.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['heavy-equipment', 'manufacturer', 'richards-bay', 'heavy-fabrication', 'kzn'],
  },
  // ── PAPER & FORESTRY ─────────────────────────────────────────
  {
    company_name: 'York Timber Holdings Ltd',
    trading_name: 'York Timbers',
    industry: 'Forestry & Timber Processing',
    website: 'https://www.york.co.za',
    company_size: '500+',
    address: '3 Main Street',
    city: 'Sabie',
    province: 'Mpumalanga',
    country: 'South Africa',
    decision_maker_name: '',
    decision_maker_title: 'Processing Plants General Manager / Fleet Manager',
    decision_maker_email: '',
    decision_maker_phone: '+27 13 764 9200',
    source_name: 'ai_scraper',
    ai_confidence: 77,
    ai_reasoning: 'SA largest solid wood processor (lumber and plywood). JSE-listed since 1946. 5,954 employees. Owns plantations + processing plants. Segments: Processing plants, Wholesale, Forestry, Fleet, Agriculture. Heavy timber bundles, lumber packs, and plywood stacks all need forklifts. Multiple sawmills and wholesale distribution points across Mpumalanga.',
    buy_probability: 8,
    qualification_status: 'new',
    tags: ['forestry', 'timber', 'sawmill', 'mpumalanga', 'multi-site', 'heavy-loads'],
  },
];

async function seed() {
  console.log(`Seeding ${leads.length} leads...`);

  // Insert all leads
  const { data, error } = await supabase
    .from('leads')
    .insert(leads.map((lead) => ({
      ...lead,
      id: crypto.randomUUID(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })));

  if (error) {
    console.error('Error seeding leads:', error.message);
    process.exit(1);
  }

  console.log(`Successfully seeded ${leads.length} leads.`);
  console.log('Lead breakdown:');
  const byIndustry = {};
  const byProvince = {};
  const byStatus = {};
  leads.forEach((l) => {
    byIndustry[l.industry] = (byIndustry[l.industry] || 0) + 1;
    byProvince[l.province] = (byProvince[l.province] || 0) + 1;
    byStatus[l.qualification_status] = (byStatus[l.qualification_status] || 0) + 1;
  });
  console.log('  By Industry:', byIndustry);
  console.log('  By Province:', byProvince);
  console.log('  By Status:', byStatus);
}

seed();
